title: Andrew Blog
author:
#   name: Andrew 
#   email: andrewshin8@gmail.com
 

# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
#   date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
#   social_links:
#     - { platform: github,         user_url: "https://github.com/jekyll/minima" }
#     - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
header_pages:
  - about.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false
